import type { AppDatabase } from '@/db/database';
import { MEDAL_LABELS } from '@/lib/calculations/judo-stats';

/**
 * Keeps the auto-generated medal achievement for a competition in sync with
 * its current medal/status, without ever duplicating it (spec 9.4). Call
 * this after every competition create/update.
 */
export async function syncCompetitionAchievement(db: AppDatabase, competitionId: string): Promise<void> {
  const competition = await db.judoCompetitions.get(competitionId);
  const existing = await db.achievements
    .where('competitionId')
    .equals(competitionId)
    .filter((achievement) => achievement.autoGenerated)
    .first();

  const shouldHaveMedalAchievement =
    competition && competition.status === 'completed' && competition.medal && competition.medal !== 'none';

  if (!shouldHaveMedalAchievement) {
    if (existing) await db.achievements.delete(existing.id);
    return;
  }

  const medalLabel = MEDAL_LABELS[competition.medal as 'gold' | 'silver' | 'bronze'];
  const record = {
    title: `מדליית ${medalLabel} — ${competition.name}`,
    achievedOn: competition.startsAt,
    type: 'competition' as const,
    competitionId: competition.id,
    autoGenerated: true,
  };

  if (existing) {
    await db.achievements.update(existing.id, record);
  } else {
    await db.achievements.add({ id: crypto.randomUUID(), ...record });
  }
}
