import { describe, expect, it } from 'vitest';
import { AppDatabase } from '@/db/database';
import { syncCompetitionAchievement } from '@/lib/judo-achievements';

function baseCompetition(overrides: Partial<Parameters<AppDatabase['judoCompetitions']['put']>[0]> = {}) {
  return {
    id: 'comp-1',
    name: 'גביע הארץ',
    startsAt: '2026-03-01T09:00:00.000Z',
    weightClassKg: 73,
    status: 'planned' as const,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
  };
}

describe('syncCompetitionAchievement', () => {
  it('creates an achievement once the competition is completed with a medal', async () => {
    const db = new AppDatabase('test-judo-ach-1');
    await db.judoCompetitions.put(baseCompetition({ status: 'completed', medal: 'gold' }));

    await syncCompetitionAchievement(db, 'comp-1');

    const achievements = await db.achievements.toArray();
    expect(achievements).toHaveLength(1);
    expect(achievements[0]).toMatchObject({ autoGenerated: true, competitionId: 'comp-1' });
    expect(achievements[0].title).toContain('זהב');

    await db.delete();
  });

  it('does not duplicate on repeated syncs, and updates the medal in place', async () => {
    const db = new AppDatabase('test-judo-ach-2');
    await db.judoCompetitions.put(baseCompetition({ status: 'completed', medal: 'gold' }));
    await syncCompetitionAchievement(db, 'comp-1');
    await syncCompetitionAchievement(db, 'comp-1');

    let achievements = await db.achievements.toArray();
    expect(achievements).toHaveLength(1);

    await db.judoCompetitions.update('comp-1', { medal: 'silver' });
    await syncCompetitionAchievement(db, 'comp-1');

    achievements = await db.achievements.toArray();
    expect(achievements).toHaveLength(1);
    expect(achievements[0].title).toContain('כסף');

    await db.delete();
  });

  it('removes the auto-achievement if the medal is later cleared', async () => {
    const db = new AppDatabase('test-judo-ach-3');
    await db.judoCompetitions.put(baseCompetition({ status: 'completed', medal: 'bronze' }));
    await syncCompetitionAchievement(db, 'comp-1');
    expect(await db.achievements.count()).toBe(1);

    await db.judoCompetitions.update('comp-1', { medal: 'none' });
    await syncCompetitionAchievement(db, 'comp-1');
    expect(await db.achievements.count()).toBe(0);

    await db.delete();
  });

  it('leaves manually created achievements untouched', async () => {
    const db = new AppDatabase('test-judo-ach-4');
    await db.judoCompetitions.put(baseCompetition({ status: 'completed', medal: 'gold' }));
    await db.achievements.add({
      id: 'manual-1',
      title: 'חגורה שחורה',
      achievedOn: '2025-01-01T00:00:00.000Z',
      type: 'belt',
      autoGenerated: false,
    });

    await syncCompetitionAchievement(db, 'comp-1');

    const achievements = await db.achievements.toArray();
    expect(achievements).toHaveLength(2);
    expect(achievements.some((achievement) => achievement.id === 'manual-1')).toBe(true);

    await db.delete();
  });
});
