import { useState } from 'react';
import { Link } from 'react-router-dom';
import { format } from 'date-fns';
import { ArrowRight } from 'lucide-react';
import { db } from '@/db/database';
import { Button } from '@/components/Button';
import { Card, EmptyState } from '@/components/Card';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { useAchievements, useCompetitions } from '@/features/judo/useCompetitions';
import type { Achievement } from '@/types';

const TYPE_LABELS: Record<NonNullable<Achievement['type']>, string> = {
  competition: 'תחרות',
  belt: 'חגורה',
  technique: 'טכניקה',
  personal: 'אישי',
  other: 'אחר',
};

interface AchievementFormState {
  title: string;
  achievedOn: string;
  note: string;
  type: '' | NonNullable<Achievement['type']>;
  competitionId: string;
}

function emptyAchievementForm(): AchievementFormState {
  return { title: '', achievedOn: format(new Date(), 'yyyy-MM-dd'), note: '', type: '', competitionId: '' };
}

function AchievementForm({
  competitions,
  onCancel,
  onSave,
}: {
  competitions: Array<{ id: string; name: string }>;
  onCancel: () => void;
  onSave: (values: AchievementFormState) => Promise<void>;
}) {
  const [values, setValues] = useState(emptyAchievementForm());
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);

  const submit = async () => {
    if (!values.title.trim() || !values.achievedOn) {
      setError('נא למלא כותרת ותאריך');
      return;
    }
    setError('');
    setSaving(true);
    try {
      await onSave(values);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <label className="flex flex-col gap-1 text-sm">
        כותרת
        <input className="input" value={values.title} onChange={(event) => setValues({ ...values, title: event.target.value })} />
      </label>
      <div className="grid grid-cols-2 gap-3">
        <label className="flex flex-col gap-1 text-sm">
          תאריך
          <input
            type="date"
            className="input"
            value={values.achievedOn}
            onChange={(event) => setValues({ ...values, achievedOn: event.target.value })}
          />
        </label>
        <label className="flex flex-col gap-1 text-sm">
          סוג (אופציונלי)
          <select
            className="input"
            value={values.type}
            onChange={(event) => setValues({ ...values, type: event.target.value as AchievementFormState['type'] })}
          >
            <option value="">—</option>
            {Object.entries(TYPE_LABELS).map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>
        </label>
      </div>
      {competitions.length > 0 ? (
        <label className="flex flex-col gap-1 text-sm">
          קישור לתחרות (אופציונלי)
          <select
            className="input"
            value={values.competitionId}
            onChange={(event) => setValues({ ...values, competitionId: event.target.value })}
          >
            <option value="">—</option>
            {competitions.map((competition) => (
              <option key={competition.id} value={competition.id}>
                {competition.name}
              </option>
            ))}
          </select>
        </label>
      ) : null}
      <label className="flex flex-col gap-1 text-sm">
        הערה (אופציונלי)
        <textarea className="input" value={values.note} onChange={(event) => setValues({ ...values, note: event.target.value })} />
      </label>
      {error ? <p className="text-sm text-red-500">{error}</p> : null}
      <div className="flex gap-2">
        <Button onClick={submit} disabled={saving}>
          שמירה
        </Button>
        <Button variant="secondary" onClick={onCancel} disabled={saving}>
          ביטול
        </Button>
      </div>
    </div>
  );
}

export function AchievementsScreen() {
  const achievements = useAchievements();
  const competitions = useCompetitions();
  const [adding, setAdding] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const createAchievement = async (values: AchievementFormState) => {
    await db.achievements.add({
      id: crypto.randomUUID(),
      title: values.title.trim(),
      achievedOn: new Date(values.achievedOn).toISOString(),
      note: values.note.trim() || undefined,
      type: values.type || undefined,
      competitionId: values.competitionId || undefined,
      autoGenerated: false,
    });
    setAdding(false);
  };

  const deleteAchievement = async () => {
    if (!deletingId) return;
    await db.achievements.delete(deletingId);
    setDeletingId(null);
  };

  return (
    <div className="safe-x flex flex-col gap-4 p-4 pb-8">
      <Link to="/judo" className="flex items-center gap-1 text-sm text-slate-500 dark:text-slate-400">
        <ArrowRight size={16} /> חזרה ללוח התחרויות
      </Link>
      <h1 className="text-2xl font-bold">הישגים</h1>

      {achievements === undefined ? null : achievements.length === 0 ? (
        <EmptyState title="אין עדיין הישגים" description="הוסיפו הישג ראשון למטה." />
      ) : (
        <Card>
          <ul>
            {achievements.map((achievement) => (
              <li
                key={achievement.id}
                className="flex items-center gap-2 border-b border-slate-200 py-2 last:border-b-0 dark:border-slate-800"
              >
                <div className="flex-1">
                  <span className="block font-medium">{achievement.title}</span>
                  <span className="block text-xs text-slate-500 dark:text-slate-400">
                    {format(new Date(achievement.achievedOn), 'dd/MM/yyyy')}
                    {achievement.type ? ` · ${TYPE_LABELS[achievement.type]}` : ''}
                    {achievement.note ? ` · ${achievement.note}` : ''}
                  </span>
                </div>
                <Button variant="ghost" className="px-2 text-xs text-red-500" onClick={() => setDeletingId(achievement.id)}>
                  מחיקה
                </Button>
              </li>
            ))}
          </ul>
        </Card>
      )}

      <Card>
        {adding ? (
          <AchievementForm competitions={competitions ?? []} onCancel={() => setAdding(false)} onSave={createAchievement} />
        ) : (
          <Button variant="secondary" onClick={() => setAdding(true)} className="w-full">
            + הישג חדש
          </Button>
        )}
      </Card>

      <ConfirmDialog
        open={deletingId !== null}
        title="מחיקת הישג"
        description="לא ניתן לשחזר הישג שנמחק."
        confirmLabel="מחיקה"
        onConfirm={deleteAchievement}
        onCancel={() => setDeletingId(null)}
      />
    </div>
  );
}
