export interface UserProfile {
  id: 'local-user';
  birthDate?: string;
  ageFallback?: number;
  biologicalSex: 'male' | 'female';
  heightCm: number;
  currentWeightKg: number;
  nonExerciseActivityLevel: 'sedentary' | 'light' | 'moderate' | 'high';
  proteinGramsPerKg: number;
  oneRmFormula: 'epley' | 'brzycki';
  theme: 'dark' | 'light' | 'system';
  onboardingCompleted: boolean;
  createdAt: string;
  updatedAt: string;
}

export type ExerciseMetricType = 'weight' | 'reps' | 'time' | 'distance' | 'score';

export interface Exercise {
  id: string;
  nameHe: string;
  nameEn: string;
  aliases: string[];
  category: string;
  metricType: ExerciseMetricType;
  builtIn: boolean;
  favorite: boolean;
  hidden: boolean;
}

export interface StrengthResult {
  id: string;
  exerciseId: string;
  performedAt: string;
  weightKg?: number;
  reps?: number;
  value?: number;
  rpe?: number;
  note?: string;
  estimatedOneRmEpley?: number;
  estimatedOneRmBrzycki?: number;
}

export interface ExerciseGoal {
  id: string;
  exerciseId: string;
  targetValue: number;
  targetDate?: string;
  achievedAt?: string;
  createdAt: string;
}

export interface JudoCompetition {
  id: string;
  name: string;
  startsAt: string;
  weighInAt?: string;
  location?: string;
  address?: string;
  weightClassKg: number;
  targetWeighInKg?: number;
  status: 'planned' | 'completed' | 'cancelled';
  finalPlace?: number;
  medal?: 'gold' | 'silver' | 'bronze' | 'none';
  wins?: number;
  losses?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Achievement {
  id: string;
  title: string;
  achievedOn: string;
  type?: 'competition' | 'belt' | 'technique' | 'personal' | 'other';
  note?: string;
  competitionId?: string;
  autoGenerated: boolean;
}

export type SportType = 'judo' | 'crossfit' | 'strength' | 'run' | 'walk' | 'other';
export type Intensity = 'low' | 'moderate' | 'high';

export interface WeeklyWorkoutTemplate {
  id: string;
  weekday: number;
  sportType: SportType;
  title: string;
  plannedStartTime?: string;
  durationMinutes: number;
  intensity: Intensity;
  metValue: number;
  active: boolean;
}

export interface WorkoutLog {
  id: string;
  templateId?: string;
  performedAt: string;
  sportType: string;
  title: string;
  durationMinutes: number;
  intensity: Intensity;
  metValue: number;
  estimatedNetKcal: number;
  note?: string;
}

export interface WeightEntry {
  id: string;
  measuredAt: string;
  weightKg: number;
  note?: string;
  excludedFromTrend: boolean;
}

export interface WeightGoal {
  id: string;
  startDate: string;
  startWeightKg: number;
  targetWeightKg: number;
  targetDate: string;
  linkedCompetitionId?: string;
  active: boolean;
  createdAt: string;
}

export type FoodSource = 'local' | 'usda' | 'open-food-facts' | 'custom';

export interface FoodReference {
  id: string;
  canonicalNameHe: string;
  canonicalNameEn: string;
  aliases: string[];
  kcalPer100g: number;
  proteinPer100g: number;
  servingOptions: Array<{ label: string; grams: number }>;
  source: FoodSource;
  sourceId?: string;
  cachedAt?: string;
}

export type Confidence = 'high' | 'medium' | 'low';

export interface FoodLogItem {
  id: string;
  mealId: string;
  foodReferenceId?: string;
  displayName: string;
  amount: number;
  unit: string;
  estimatedGrams: number;
  kcal: number;
  proteinGrams: number;
  confidence: Confidence;
  assumption?: string;
  conservativeMultiplier: number;
  source: string;
  userEdited: boolean;
}

export interface MealLog {
  id: string;
  eatenAt: string;
  originalText: string;
  dayCompleteAfterThisMeal?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SavedMeal {
  id: string;
  name: string;
  items: Array<{
    foodReferenceId?: string;
    displayName: string;
    estimatedGrams: number;
    kcal: number;
    proteinGrams: number;
  }>;
  createdAt: string;
  updatedAt: string;
}

export interface AppSettings {
  id: 'settings';
  usdaApiKey?: string;
  notificationMode: 'in-app' | 'calendar' | 'web-push';
  schemaVersion: number;
}
