import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '@/App';
import { db } from '@/db/database';

// HashRouter reads window.location.hash, which jsdom keeps across tests in the
// same file (unlike a real browser tab reload), so reset it before each test.
beforeEach(() => {
  window.location.hash = '';
});

afterEach(async () => {
  await Promise.all(db.tables.map((table) => table.clear()));
});

async function completeOnboardingAndOpenJudo(user: ReturnType<typeof userEvent.setup>) {
  render(<App />);
  await user.clear(await screen.findByLabelText('גיל (אם אין תאריך)'));
  await user.type(screen.getByLabelText('גיל (אם אין תאריך)'), '30');
  await user.clear(screen.getByLabelText('גובה (ס״מ)'));
  await user.type(screen.getByLabelText('גובה (ס״מ)'), '178');
  await user.clear(screen.getByLabelText('משקל נוכחי (ק״ג)'));
  await user.type(screen.getByLabelText('משקל נוכחי (ק״ג)'), '82');
  await user.click(screen.getByRole('button', { name: 'התחלה' }));
  await screen.findByRole('heading', { name: 'בית' });
  await user.click(screen.getByRole('link', { name: 'ג׳ודו' }));
  await screen.findByRole('heading', { name: 'ג׳ודו' });
}

describe('Judo module', () => {
  it('adding a competition, editing it, exporting to calendar and entering a result', async () => {
    const user = userEvent.setup();
    await completeOnboardingAndOpenJudo(user);

    expect(screen.getByText('אין עדיין תחרויות')).toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: '+ תחרות חדשה' }));
    await user.type(screen.getByLabelText('שם התחרות'), 'גביע הארץ 2027');
    await user.type(screen.getByLabelText('תאריך התחלה'), '2027-01-15');
    await user.type(screen.getByLabelText('קטגוריית משקל (ק״ג)'), '73');
    await user.click(screen.getByRole('button', { name: 'שמירה' }));

    const listLink = await screen.findByRole('link', { name: /גביע הארץ 2027/ });
    await user.click(listLink);
    await screen.findByRole('heading', { name: 'גביע הארץ 2027' });

    let competitions = await db.judoCompetitions.toArray();
    expect(competitions).toHaveLength(1);
    expect(competitions[0]).toMatchObject({ name: 'גביע הארץ 2027', weightClassKg: 73, status: 'planned' });

    // Edit: change location, mark completed and enter a result (medal + wins/losses).
    await user.click(screen.getByRole('button', { name: 'עריכה' }));
    await user.type(screen.getByLabelText('מקום'), 'היכל הספורט');
    await user.click(screen.getByLabelText('הושלמה'));
    await user.selectOptions(screen.getByLabelText('מדליה'), 'gold');
    await user.type(screen.getByLabelText('ניצחונות'), '3');
    await user.type(screen.getByLabelText('הפסדים'), '1');
    await user.click(screen.getByRole('button', { name: 'שמירה' }));

    await screen.findByText('מדליה: זהב');
    expect(screen.getByText('ניצחונות / הפסדים: 3 / 1')).toBeInTheDocument();
    expect(screen.getByText('מקום: היכל הספורט')).toBeInTheDocument();

    competitions = await db.judoCompetitions.toArray();
    expect(competitions[0]).toMatchObject({
      status: 'completed',
      medal: 'gold',
      wins: 3,
      losses: 1,
      location: 'היכל הספורט',
    });

    await waitFor(async () => {
      const achievements = await db.achievements.toArray();
      expect(achievements).toHaveLength(1);
      expect(achievements[0]).toMatchObject({ autoGenerated: true, competitionId: competitions[0].id });
      expect(achievements[0].title).toContain('זהב');
    });

    // Export to calendar (.ics) — jsdom has no Blob URL support, so stub it.
    const createObjectURL = vi.fn(() => 'blob:mock-url');
    const revokeObjectURL = vi.fn();
    URL.createObjectURL = createObjectURL;
    URL.revokeObjectURL = revokeObjectURL;

    await user.click(screen.getByRole('button', { name: 'הוסף ליומן' }));

    expect(createObjectURL).toHaveBeenCalledTimes(1);
    const blob = createObjectURL.mock.calls[0][0] as Blob;
    const icsText = await blob.text();
    expect(icsText).toContain('SUMMARY:גביע הארץ 2027');
    expect(icsText).toContain('LOCATION:היכל הספורט');
    expect(revokeObjectURL).toHaveBeenCalledWith('blob:mock-url');

    // Achievements screen reflects the auto-generated medal achievement.
    await user.click(screen.getByRole('link', { name: 'חזרה ללוח התחרויות' }));
    await screen.findByRole('heading', { name: 'ג׳ודו' });
    await user.click(screen.getByRole('link', { name: 'הישגים' }));
    expect(await screen.findByText(/מדליית זהב — גביע הארץ 2027/)).toBeInTheDocument();
  });
});
